### ISSUE TITLE
multiple http endpoints per agent

### ISSUE THREAD

**Issue by rg2011** [andydunstall/piko#216]
First of all, thanks for sharing this application.

Is it supported to have several http listeners in the same agent?

I am running release 0.6.6 of the piko agent, with two http listeners, and the agent panics with:

```
talos-api-access-68487ccbb7-hjwms piko panic: duplicate metrics collector registration attempted
talos-api-access-68487ccbb7-hjwms piko 
talos-api-access-68487ccbb7-hjwms piko goroutine 1 [running]:
talos-api-access-68487ccbb7-hjwms piko github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(...)
talos-api-access-68487ccbb7-hjwms piko  /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.20.5/prometheus/registry.go:406
talos-api-access-68487ccbb7-hjwms piko github.com/andydunstall/piko/pkg/middleware.(*Metrics).Register(0xc0003b0200, 0xc00012e550)
talos-api-access-68487ccbb7-hjwms piko  /home/runner/work/piko/piko/pkg/middleware/metrics.go:95 +0x15e
talos-api-access-68487ccbb7-hjwms piko github.com/andydunstall/piko/agent/reverseproxy.NewServer({{0xc000146300, 0x11}, {0xc000134670, 0xe}, {0xc0001346c0, 0x4}, 0x0, 0x37e11d600, {{0x0, 0x0}, ...}}, ...)
talos-api-access-68487ccbb7-hjwms piko  /home/runner/work/piko/piko/agent/reverseproxy/server.go:55 +0x3b9
talos-api-access-68487ccbb7-hjwms piko github.com/andydunstall/piko/cli/agent.runAgent(0xc000164000, {0xf0a1a0, 0xc00012e4b0})
talos-api-access-68487ccbb7-hjwms piko  /home/runner/work/piko/piko/cli/agent/command.go:141 +0x770
talos-api-access-68487ccbb7-hjwms piko github.com/andydunstall/piko/cli/agent.NewCommand.newStartCommand.func3(0xc00013f100?, {0xd98a45?, 0x4?, 0xd989fd?})
talos-api-access-68487ccbb7-hjwms piko  /home/runner/work/piko/piko/cli/agent/start.go:44 +0x36
talos-api-access-68487ccbb7-hjwms piko github.com/spf13/cobra.(*Command).execute(0xc000162c08, {0xc00012d710, 0x3, 0x3})
talos-api-access-68487ccbb7-hjwms piko  /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
talos-api-access-68487ccbb7-hjwms piko github.com/spf13/cobra.(*Command).ExecuteC(0xc000140308)
talos-api-access-68487ccbb7-hjwms piko  /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
talos-api-access-68487ccbb7-hjwms piko github.com/spf13/cobra.(*Command).Execute(...)
talos-api-access-68487ccbb7-hjwms piko  /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
talos-api-access-68487ccbb7-hjwms piko github.com/andydunstall/piko/cli.Start()
talos-api-access-68487ccbb7-hjwms piko  /home/runner/work/piko/piko/cli/cli.go:5 +0x18
talos-api-access-68487ccbb7-hjwms piko main.main()
talos-api-access-68487ccbb7-hjwms piko  /home/runner/work/piko/piko/main.go:10 +0x13
- talos-api-access-68487ccbb7-hjwms › piko
-
```

The agent config is:

```yaml
# Listeners contains the set of listeners to register. Each listener has an
# endpoint ID, address to forward connections to, whether to log each request
# and a timeout to forward requests to the upstreams.
listeners:

  - endpoint_id: talosapi.${ENDPOINT}
    addr: localhost:50000
    protocol: http
    access_log: false
    timeout: 15s

  - endpoint_id: k8sapi.${ENDPOINT}
    addr: localhost:6443
    protocol: http
    access_log: false
    timeout: 15s

connect:
  url: ${UPSTREAM_HOST}
  token: "${TOKEN}"
  timeout: 30s
  tls:
    insecure_skip_verify: true

server:
  enabled: false
  bind_addr: ":5000"

log:
  level: info
  subsystems: []

grace_period: 1m0s
```

I guess the problem is that each listener is trying to register its own metrics with the same namespace, subsystem and name. Each call to `reverseproxy.NewServer` creates a new set of metrics in the `agent` subsystem:

https://github.com/andydunstall/piko/blob/799062a8cc608c2e2fb7ea672fc7defb13cf7e00/agent/reverseproxy/server.go#L53

And then `middleware.NewMetrics` always uses the same name and namespace for the metrics it creates:

https://github.com/andydunstall/piko/blob/799062a8cc608c2e2fb7ea672fc7defb13cf7e00/pkg/middleware/metrics.go#L20-L29

So metrics for separate listeners end up with the same subsystem, namespace and name.

If running several http listeners in the same agent is not supported, it's ok, I will create separate agents.

But if this is a bug, I could contribute a fix.
